name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
jobs:
  build-and-test:
    # Ref: https://github.com/actions/runner-images/tree/main/images/macos
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73
          override: true
          components: clippy, rustfmt
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Rust code test
        run: cargo test
      - name: Go code test
        run: go test ./...
